services:
  m3ucrawler:
    image: ghcr.io/ginjeira/m3ucrawler:latest
    container_name: m3ucrawler
    restart: unless-stopped
    working_dir: /data
    command:
      - --telegram
      - portugal
      - --telegram-maintain
      - --loop-hours
      - "24"
      - --history-hours
      - "360"
      - --max-streams
      - "500"
      - --output-dir
      - /opt/playlists
      - --web
      - --web-port
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - /opt/m3ucrawler/runtime-data:/data
      - /opt/m3ucrawler/runtime-data/playlists:/opt/playlists
