// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using m3uCrawler.Services.Catalog;

#nullable disable

namespace m3uCrawler.Services.Catalog.Migrations
{
    [DbContext(typeof(ChannelCatalogDbContext))]
    [Migration("20260903160916_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("m3uCrawler.Services.Catalog.CanonicalChannelEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EditorialCategory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EditorialGroup")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("PublicationPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("canonical_channels", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.ChannelAliasEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CanonicalChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedAlias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalChannelId");

                    b.HasIndex("NormalizedAlias")
                        .IsUnique();

                    b.ToTable("channel_aliases", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.DispatcharrChannelOwnershipEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CanonicalChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("DispatcharrChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ownership")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalChannelId");

                    b.HasIndex("DispatcharrChannelId")
                        .IsUnique();

                    b.ToTable("dispatcharr_channel_ownerships", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.DispatcharrStreamOwnershipEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreatedBySyncRunId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DispatcharrChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DispatcharrStreamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ownership")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DispatcharrStreamId")
                        .IsUnique();

                    b.ToTable("dispatcharr_stream_ownerships", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.IdentityRuleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Disposition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedIdentity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedIdentity")
                        .IsUnique();

                    b.ToTable("identity_rules", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.ReviewItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ApprovedCanonicalChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedIdentity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonSignature")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceGroup")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedCanonicalChannelId");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.ToTable("review_items", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.SyncRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("CountCreatedCrawlerManaged")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountExcluded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountMergedIntoExternal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountProtectedExternalStreams")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountRemovedCrawlerManagedStreams")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountReviewRequired")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FinishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("sync_runs", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.ChannelAliasEntity", b =>
                {
                    b.HasOne("m3uCrawler.Services.Catalog.CanonicalChannelEntity", "CanonicalChannel")
                        .WithMany("Aliases")
                        .HasForeignKey("CanonicalChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalChannel");
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.DispatcharrChannelOwnershipEntity", b =>
                {
                    b.HasOne("m3uCrawler.Services.Catalog.CanonicalChannelEntity", "CanonicalChannel")
                        .WithMany()
                        .HasForeignKey("CanonicalChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CanonicalChannel");
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.ReviewItemEntity", b =>
                {
                    b.HasOne("m3uCrawler.Services.Catalog.CanonicalChannelEntity", "ApprovedCanonicalChannel")
                        .WithMany()
                        .HasForeignKey("ApprovedCanonicalChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedCanonicalChannel");
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.CanonicalChannelEntity", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
