// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using m3uCrawler.Services.Catalog;

#nullable disable

namespace m3uCrawler.Services.Catalog.Migrations
{
    [DbContext(typeof(ChannelCatalogDbContext))]
    [Migration("20260906100000_AddAffinityGroups")]
    partial class AddAffinityGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("m3uCrawler.Services.Catalog.AffinityGroupEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CanonicalChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalChannelId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("affinity_groups", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.AffinityMemberEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AffinityGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedMember")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AffinityGroupId");

                    b.HasIndex("NormalizedMember")
                        .IsUnique();

                    b.ToTable("affinity_members", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.AffinityGroupEntity", b =>
                {
                    b.HasOne("m3uCrawler.Services.Catalog.CanonicalChannelEntity", "CanonicalChannel")
                        .WithMany()
                        .HasForeignKey("CanonicalChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalChannel");
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.AffinityMemberEntity", b =>
                {
                    b.HasOne("m3uCrawler.Services.Catalog.AffinityGroupEntity", "AffinityGroup")
                        .WithMany("Members")
                        .HasForeignKey("AffinityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffinityGroup");
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.AffinityGroupEntity", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
