// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using m3uCrawler.Services.Catalog;

#nullable disable

namespace m3uCrawler.Services.Catalog.Migrations
{
    [DbContext(typeof(ChannelCatalogDbContext))]
    [Migration("20260911065042_AddChannelSourceObservation")]
    partial class AddChannelSourceObservation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("m3uCrawler.Services.Catalog.AffinityGroupEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CanonicalChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalChannelId");

                    b.HasIndex("CountryCode");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("affinity_groups", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.AffinityMemberEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AffinityGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedMember")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AffinityGroupId");

                    b.HasIndex("NormalizedMember")
                        .IsUnique();

                    b.ToTable("affinity_members", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.CanonicalChannelEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EditorialCategory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EditorialGroup")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("PublicationPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("canonical_channels", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.CanonicalGroupEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("canonical_groups", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.ChannelAliasEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CanonicalChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedAlias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalChannelId");

                    b.HasIndex("NormalizedAlias")
                        .IsUnique();

                    b.ToTable("channel_aliases", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.ChannelSourceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Availability")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CanonicalChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Epg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalStreamId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastTestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("MatchConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("MatchMethod")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("CanonicalChannelId", "SourceId");

                    b.ToTable("channel_sources", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.ChannelSourceObservationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Availability")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChannelSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Epg")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChannelSourceId", "ObservedAtUtc");

                    b.ToTable("channel_source_observations", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.DispatcharrChannelOwnershipEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CanonicalChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("DispatcharrChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ownership")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalChannelId");

                    b.HasIndex("DispatcharrChannelId")
                        .IsUnique();

                    b.ToTable("dispatcharr_channel_ownerships", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.DispatcharrStreamOwnershipEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreatedBySyncRunId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DispatcharrChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DispatcharrStreamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ownership")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DispatcharrStreamId")
                        .IsUnique();

                    b.ToTable("dispatcharr_stream_ownerships", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.GroupMappingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CanonicalGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceGroupTitle")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceKind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalGroupId");

                    b.HasIndex("SourceKind", "SourceGroupTitle")
                        .IsUnique();

                    b.ToTable("group_mappings", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.IdentityRuleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Disposition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedIdentity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedIdentity")
                        .IsUnique();

                    b.ToTable("identity_rules", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.ImportPolicyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcludedGroupsCsv")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetGroupsCsv")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("VodPolicy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaKind")
                        .IsUnique();

                    b.ToTable("import_policies", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.MatchingAuditEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CanonicalChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("NormalizedIdentity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonSignature")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceGroup")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AtUtc");

                    b.HasIndex("CanonicalChannelId");

                    b.HasIndex("NormalizedIdentity");

                    b.ToTable("matching_audits", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.OrderingItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CanonicalChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OrderingListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalChannelId");

                    b.HasIndex("OrderingListId", "CanonicalChannelId")
                        .IsUnique();

                    b.HasIndex("OrderingListId", "Position")
                        .IsUnique();

                    b.ToTable("ordering_items", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.OrderingListEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ordering_lists", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.PendingCountryApprovalEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedIdentity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonSignature")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceGroup")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("NormalizedIdentity");

                    b.HasIndex("State");

                    b.ToTable("pending_country_approvals", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.ReviewItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ApprovedCanonicalChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedIdentity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonSignature")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceGroup")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedCanonicalChannelId");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.ToTable("review_items", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.SourceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastDiscoveryAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastValidationAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.SourcePriorityPolicyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowFallback")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CanonicalChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriteriaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredQuality")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Scope")
                        .IsUnique();

                    b.ToTable("source_priority_policies", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.SyncRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("CountCreatedCrawlerManaged")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountExcluded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountMergedIntoExternal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountProtectedExternalStreams")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountRemovedCrawlerManagedStreams")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountReviewRequired")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FinishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("sync_runs", (string)null);
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.AffinityGroupEntity", b =>
                {
                    b.HasOne("m3uCrawler.Services.Catalog.CanonicalChannelEntity", "CanonicalChannel")
                        .WithMany()
                        .HasForeignKey("CanonicalChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CanonicalChannel");
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.AffinityMemberEntity", b =>
                {
                    b.HasOne("m3uCrawler.Services.Catalog.AffinityGroupEntity", "AffinityGroup")
                        .WithMany("Members")
                        .HasForeignKey("AffinityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffinityGroup");
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.ChannelAliasEntity", b =>
                {
                    b.HasOne("m3uCrawler.Services.Catalog.CanonicalChannelEntity", "CanonicalChannel")
                        .WithMany("Aliases")
                        .HasForeignKey("CanonicalChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalChannel");
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.ChannelSourceEntity", b =>
                {
                    b.HasOne("m3uCrawler.Services.Catalog.CanonicalChannelEntity", "CanonicalChannel")
                        .WithMany()
                        .HasForeignKey("CanonicalChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("m3uCrawler.Services.Catalog.SourceEntity", "Source")
                        .WithMany("ChannelSources")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalChannel");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.DispatcharrChannelOwnershipEntity", b =>
                {
                    b.HasOne("m3uCrawler.Services.Catalog.CanonicalChannelEntity", "CanonicalChannel")
                        .WithMany()
                        .HasForeignKey("CanonicalChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CanonicalChannel");
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.GroupMappingEntity", b =>
                {
                    b.HasOne("m3uCrawler.Services.Catalog.CanonicalGroupEntity", "CanonicalGroup")
                        .WithMany()
                        .HasForeignKey("CanonicalGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalGroup");
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.OrderingItemEntity", b =>
                {
                    b.HasOne("m3uCrawler.Services.Catalog.CanonicalChannelEntity", "CanonicalChannel")
                        .WithMany()
                        .HasForeignKey("CanonicalChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("m3uCrawler.Services.Catalog.OrderingListEntity", "OrderingList")
                        .WithMany("Items")
                        .HasForeignKey("OrderingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalChannel");

                    b.Navigation("OrderingList");
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.ReviewItemEntity", b =>
                {
                    b.HasOne("m3uCrawler.Services.Catalog.CanonicalChannelEntity", "ApprovedCanonicalChannel")
                        .WithMany()
                        .HasForeignKey("ApprovedCanonicalChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedCanonicalChannel");
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.AffinityGroupEntity", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.CanonicalChannelEntity", b =>
                {
                    b.Navigation("Aliases");
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.OrderingListEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("m3uCrawler.Services.Catalog.SourceEntity", b =>
                {
                    b.Navigation("ChannelSources");
                });
#pragma warning restore 612, 618
        }
    }
}
